---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

workspace:
  path: github.com/micro-in-cn/starter-kit

steps:
  - name: build
    image: golang:1.13-alpine
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
      GOPROXY: https://mirrors.aliyun.com/goproxy/
      GOSUMDB: off
    commands:
      - pwd
      - go version
      - cd gateway
      - go build -o ./bin/linux_amd64/micro main.go plugin.go
      - ./bin/linux_amd64/micro --version
  - name: publish
    image: plugins/docker
    settings:
      auto_tag: true
      dockerfile: gateway/Dockerfile
      context: ./gateway
      repo: hbchen/starter-kit-gateway
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
      event:
        - push
        - tag
